#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_MRQA")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void Inserttb_Catalog(tb_Catalog instance);
  partial void Updatetb_Catalog(tb_Catalog instance);
  partial void Deletetb_Catalog(tb_Catalog instance);
  partial void Inserttb_Config(tb_Config instance);
  partial void Updatetb_Config(tb_Config instance);
  partial void Deletetb_Config(tb_Config instance);
  partial void Inserttb_Question(tb_Question instance);
  partial void Updatetb_Question(tb_Question instance);
  partial void Deletetb_Question(tb_Question instance);
  partial void Inserttb_Answer(tb_Answer instance);
  partial void Updatetb_Answer(tb_Answer instance);
  partial void Deletetb_Answer(tb_Answer instance);
  partial void Inserttb_UserInfo(tb_UserInfo instance);
  partial void Updatetb_UserInfo(tb_UserInfo instance);
  partial void Deletetb_UserInfo(tb_UserInfo instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_MRQAConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<tb_Catalog> tb_Catalog
	{
		get
		{
			return this.GetTable<tb_Catalog>();
		}
	}
	
	public System.Data.Linq.Table<tb_Config> tb_Config
	{
		get
		{
			return this.GetTable<tb_Config>();
		}
	}
	
	public System.Data.Linq.Table<tb_Question> tb_Question
	{
		get
		{
			return this.GetTable<tb_Question>();
		}
	}
	
	public System.Data.Linq.Table<tb_Answer> tb_Answer
	{
		get
		{
			return this.GetTable<tb_Answer>();
		}
	}
	
	public System.Data.Linq.Table<tb_UserInfo> tb_UserInfo
	{
		get
		{
			return this.GetTable<tb_UserInfo>();
		}
	}
	
	public System.Data.Linq.Table<vw_QuestionCatalog> vw_QuestionCatalog
	{
		get
		{
			return this.GetTable<vw_QuestionCatalog>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Catalog")]
public partial class tb_Catalog : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _ParentCode;
	
	private System.Nullable<int> _Layer;
	
	private string _Name;
	
	private System.Nullable<bool> _Status;
	
	private System.Nullable<int> _DisplayOrder;
	
	private EntitySet<tb_Question> _tb_Question;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnParentCodeChanging(string value);
    partial void OnParentCodeChanged();
    partial void OnLayerChanging(System.Nullable<int> value);
    partial void OnLayerChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnStatusChanging(System.Nullable<bool> value);
    partial void OnStatusChanged();
    partial void OnDisplayOrderChanging(System.Nullable<int> value);
    partial void OnDisplayOrderChanged();
    #endregion
	
	public tb_Catalog()
	{
		this._tb_Question = new EntitySet<tb_Question>(new Action<tb_Question>(this.attach_tb_Question), new Action<tb_Question>(this.detach_tb_Question));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentCode", DbType="VarChar(50)")]
	public string ParentCode
	{
		get
		{
			return this._ParentCode;
		}
		set
		{
			if ((this._ParentCode != value))
			{
				this.OnParentCodeChanging(value);
				this.SendPropertyChanging();
				this._ParentCode = value;
				this.SendPropertyChanged("ParentCode");
				this.OnParentCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Layer", DbType="Int")]
	public System.Nullable<int> Layer
	{
		get
		{
			return this._Layer;
		}
		set
		{
			if ((this._Layer != value))
			{
				this.OnLayerChanging(value);
				this.SendPropertyChanging();
				this._Layer = value;
				this.SendPropertyChanged("Layer");
				this.OnLayerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit")]
	public System.Nullable<bool> Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayOrder", DbType="Int")]
	public System.Nullable<int> DisplayOrder
	{
		get
		{
			return this._DisplayOrder;
		}
		set
		{
			if ((this._DisplayOrder != value))
			{
				this.OnDisplayOrderChanging(value);
				this.SendPropertyChanging();
				this._DisplayOrder = value;
				this.SendPropertyChanged("DisplayOrder");
				this.OnDisplayOrderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Catalog_tb_Question", Storage="_tb_Question", ThisKey="Code", OtherKey="CatalogCode")]
	public EntitySet<tb_Question> tb_Question
	{
		get
		{
			return this._tb_Question;
		}
		set
		{
			this._tb_Question.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Question(tb_Question entity)
	{
		this.SendPropertyChanging();
		entity.tb_Catalog = this;
	}
	
	private void detach_tb_Question(tb_Question entity)
	{
		this.SendPropertyChanging();
		entity.tb_Catalog = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Config")]
public partial class tb_Config : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private System.Nullable<int> _Solved;
	
	private System.Nullable<int> _UnSolved;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnSolvedChanging(System.Nullable<int> value);
    partial void OnSolvedChanged();
    partial void OnUnSolvedChanging(System.Nullable<int> value);
    partial void OnUnSolvedChanged();
    #endregion
	
	public tb_Config()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Solved", DbType="Int")]
	public System.Nullable<int> Solved
	{
		get
		{
			return this._Solved;
		}
		set
		{
			if ((this._Solved != value))
			{
				this.OnSolvedChanging(value);
				this.SendPropertyChanging();
				this._Solved = value;
				this.SendPropertyChanged("Solved");
				this.OnSolvedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnSolved", DbType="Int")]
	public System.Nullable<int> UnSolved
	{
		get
		{
			return this._UnSolved;
		}
		set
		{
			if ((this._UnSolved != value))
			{
				this.OnUnSolvedChanging(value);
				this.SendPropertyChanging();
				this._UnSolved = value;
				this.SendPropertyChanged("UnSolved");
				this.OnUnSolvedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Question")]
public partial class tb_Question : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _CatalogCode;
	
	private string _UserCode;
	
	private string _Title;
	
	private string _Text;
	
	private System.Nullable<int> _Mark;
	
	private System.Nullable<System.DateTime> _PostDatetime;
	
	private System.Nullable<int> _State;
	
	private EntitySet<tb_Answer> _tb_Answer;
	
	private EntityRef<tb_Catalog> _tb_Catalog;
	
	private EntityRef<tb_UserInfo> _tb_UserInfo;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnCatalogCodeChanging(string value);
    partial void OnCatalogCodeChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnMarkChanging(System.Nullable<int> value);
    partial void OnMarkChanged();
    partial void OnPostDatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPostDatetimeChanged();
    partial void OnStateChanging(System.Nullable<int> value);
    partial void OnStateChanged();
    #endregion
	
	public tb_Question()
	{
		this._tb_Answer = new EntitySet<tb_Answer>(new Action<tb_Answer>(this.attach_tb_Answer), new Action<tb_Answer>(this.detach_tb_Answer));
		this._tb_Catalog = default(EntityRef<tb_Catalog>);
		this._tb_UserInfo = default(EntityRef<tb_UserInfo>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogCode", DbType="VarChar(50)")]
	public string CatalogCode
	{
		get
		{
			return this._CatalogCode;
		}
		set
		{
			if ((this._CatalogCode != value))
			{
				if (this._tb_Catalog.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCatalogCodeChanging(value);
				this.SendPropertyChanging();
				this._CatalogCode = value;
				this.SendPropertyChanged("CatalogCode");
				this.OnCatalogCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="VarChar(50)")]
	public string UserCode
	{
		get
		{
			return this._UserCode;
		}
		set
		{
			if ((this._UserCode != value))
			{
				if (this._tb_UserInfo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserCodeChanging(value);
				this.SendPropertyChanging();
				this._UserCode = value;
				this.SendPropertyChanged("UserCode");
				this.OnUserCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Text
	{
		get
		{
			return this._Text;
		}
		set
		{
			if ((this._Text != value))
			{
				this.OnTextChanging(value);
				this.SendPropertyChanging();
				this._Text = value;
				this.SendPropertyChanged("Text");
				this.OnTextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
	public System.Nullable<int> Mark
	{
		get
		{
			return this._Mark;
		}
		set
		{
			if ((this._Mark != value))
			{
				this.OnMarkChanging(value);
				this.SendPropertyChanging();
				this._Mark = value;
				this.SendPropertyChanged("Mark");
				this.OnMarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDatetime", DbType="DateTime")]
	public System.Nullable<System.DateTime> PostDatetime
	{
		get
		{
			return this._PostDatetime;
		}
		set
		{
			if ((this._PostDatetime != value))
			{
				this.OnPostDatetimeChanging(value);
				this.SendPropertyChanging();
				this._PostDatetime = value;
				this.SendPropertyChanged("PostDatetime");
				this.OnPostDatetimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int")]
	public System.Nullable<int> State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Question_tb_Answer", Storage="_tb_Answer", ThisKey="Code", OtherKey="QuestionCode")]
	public EntitySet<tb_Answer> tb_Answer
	{
		get
		{
			return this._tb_Answer;
		}
		set
		{
			this._tb_Answer.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Catalog_tb_Question", Storage="_tb_Catalog", ThisKey="CatalogCode", OtherKey="Code", IsForeignKey=true)]
	public tb_Catalog tb_Catalog
	{
		get
		{
			return this._tb_Catalog.Entity;
		}
		set
		{
			tb_Catalog previousValue = this._tb_Catalog.Entity;
			if (((previousValue != value) 
						|| (this._tb_Catalog.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Catalog.Entity = null;
					previousValue.tb_Question.Remove(this);
				}
				this._tb_Catalog.Entity = value;
				if ((value != null))
				{
					value.tb_Question.Add(this);
					this._CatalogCode = value.Code;
				}
				else
				{
					this._CatalogCode = default(string);
				}
				this.SendPropertyChanged("tb_Catalog");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_UserInfo_tb_Question", Storage="_tb_UserInfo", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
	public tb_UserInfo tb_UserInfo
	{
		get
		{
			return this._tb_UserInfo.Entity;
		}
		set
		{
			tb_UserInfo previousValue = this._tb_UserInfo.Entity;
			if (((previousValue != value) 
						|| (this._tb_UserInfo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_UserInfo.Entity = null;
					previousValue.tb_Question.Remove(this);
				}
				this._tb_UserInfo.Entity = value;
				if ((value != null))
				{
					value.tb_Question.Add(this);
					this._UserCode = value.Code;
				}
				else
				{
					this._UserCode = default(string);
				}
				this.SendPropertyChanged("tb_UserInfo");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Answer(tb_Answer entity)
	{
		this.SendPropertyChanging();
		entity.tb_Question = this;
	}
	
	private void detach_tb_Answer(tb_Answer entity)
	{
		this.SendPropertyChanging();
		entity.tb_Question = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Answer")]
public partial class tb_Answer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _QuestionCode;
	
	private string _UserCode;
	
	private string _Title;
	
	private string _Text;
	
	private System.Nullable<bool> _BestAnswer;
	
	private System.Nullable<System.DateTime> _PostDatetime;
	
	private System.Nullable<int> _VoteNice;
	
	private System.Nullable<int> _VoteBad;
	
	private EntityRef<tb_Question> _tb_Question;
	
	private EntityRef<tb_UserInfo> _tb_UserInfo;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnQuestionCodeChanging(string value);
    partial void OnQuestionCodeChanged();
    partial void OnUserCodeChanging(string value);
    partial void OnUserCodeChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnTextChanging(string value);
    partial void OnTextChanged();
    partial void OnBestAnswerChanging(System.Nullable<bool> value);
    partial void OnBestAnswerChanged();
    partial void OnPostDatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnPostDatetimeChanged();
    partial void OnVoteNiceChanging(System.Nullable<int> value);
    partial void OnVoteNiceChanged();
    partial void OnVoteBadChanging(System.Nullable<int> value);
    partial void OnVoteBadChanged();
    #endregion
	
	public tb_Answer()
	{
		this._tb_Question = default(EntityRef<tb_Question>);
		this._tb_UserInfo = default(EntityRef<tb_UserInfo>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionCode", DbType="VarChar(50)")]
	public string QuestionCode
	{
		get
		{
			return this._QuestionCode;
		}
		set
		{
			if ((this._QuestionCode != value))
			{
				if (this._tb_Question.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnQuestionCodeChanging(value);
				this.SendPropertyChanging();
				this._QuestionCode = value;
				this.SendPropertyChanged("QuestionCode");
				this.OnQuestionCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserCode", DbType="VarChar(50)")]
	public string UserCode
	{
		get
		{
			return this._UserCode;
		}
		set
		{
			if ((this._UserCode != value))
			{
				if (this._tb_UserInfo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnUserCodeChanging(value);
				this.SendPropertyChanging();
				this._UserCode = value;
				this.SendPropertyChanged("UserCode");
				this.OnUserCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Text", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string Text
	{
		get
		{
			return this._Text;
		}
		set
		{
			if ((this._Text != value))
			{
				this.OnTextChanging(value);
				this.SendPropertyChanging();
				this._Text = value;
				this.SendPropertyChanged("Text");
				this.OnTextChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BestAnswer", DbType="Bit")]
	public System.Nullable<bool> BestAnswer
	{
		get
		{
			return this._BestAnswer;
		}
		set
		{
			if ((this._BestAnswer != value))
			{
				this.OnBestAnswerChanging(value);
				this.SendPropertyChanging();
				this._BestAnswer = value;
				this.SendPropertyChanged("BestAnswer");
				this.OnBestAnswerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PostDatetime", DbType="DateTime")]
	public System.Nullable<System.DateTime> PostDatetime
	{
		get
		{
			return this._PostDatetime;
		}
		set
		{
			if ((this._PostDatetime != value))
			{
				this.OnPostDatetimeChanging(value);
				this.SendPropertyChanging();
				this._PostDatetime = value;
				this.SendPropertyChanged("PostDatetime");
				this.OnPostDatetimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoteNice", DbType="Int")]
	public System.Nullable<int> VoteNice
	{
		get
		{
			return this._VoteNice;
		}
		set
		{
			if ((this._VoteNice != value))
			{
				this.OnVoteNiceChanging(value);
				this.SendPropertyChanging();
				this._VoteNice = value;
				this.SendPropertyChanged("VoteNice");
				this.OnVoteNiceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoteBad", DbType="Int")]
	public System.Nullable<int> VoteBad
	{
		get
		{
			return this._VoteBad;
		}
		set
		{
			if ((this._VoteBad != value))
			{
				this.OnVoteBadChanging(value);
				this.SendPropertyChanging();
				this._VoteBad = value;
				this.SendPropertyChanged("VoteBad");
				this.OnVoteBadChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Question_tb_Answer", Storage="_tb_Question", ThisKey="QuestionCode", OtherKey="Code", IsForeignKey=true)]
	public tb_Question tb_Question
	{
		get
		{
			return this._tb_Question.Entity;
		}
		set
		{
			tb_Question previousValue = this._tb_Question.Entity;
			if (((previousValue != value) 
						|| (this._tb_Question.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_Question.Entity = null;
					previousValue.tb_Answer.Remove(this);
				}
				this._tb_Question.Entity = value;
				if ((value != null))
				{
					value.tb_Answer.Add(this);
					this._QuestionCode = value.Code;
				}
				else
				{
					this._QuestionCode = default(string);
				}
				this.SendPropertyChanged("tb_Question");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_UserInfo_tb_Answer", Storage="_tb_UserInfo", ThisKey="UserCode", OtherKey="Code", IsForeignKey=true)]
	public tb_UserInfo tb_UserInfo
	{
		get
		{
			return this._tb_UserInfo.Entity;
		}
		set
		{
			tb_UserInfo previousValue = this._tb_UserInfo.Entity;
			if (((previousValue != value) 
						|| (this._tb_UserInfo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tb_UserInfo.Entity = null;
					previousValue.tb_Answer.Remove(this);
				}
				this._tb_UserInfo.Entity = value;
				if ((value != null))
				{
					value.tb_Answer.Add(this);
					this._UserCode = value.Code;
				}
				else
				{
					this._UserCode = default(string);
				}
				this.SendPropertyChanged("tb_UserInfo");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_UserInfo")]
public partial class tb_UserInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Code;
	
	private string _UserName;
	
	private string _Password;
	
	private string _Sex;
	
	private string _Email;
	
	private System.Nullable<int> _Mark;
	
	private System.Nullable<int> _RewardMark;
	
	private System.Nullable<int> _PaidMark;
	
	private System.Nullable<int> _ACount;
	
	private System.Nullable<int> _AAcceptCount;
	
	private System.Nullable<int> _QSolvedCount;
	
	private System.Nullable<int> _QUnsolveCount;
	
	private System.Nullable<int> _QCancelledCount;
	
	private System.Nullable<System.DateTime> _CreatedDate;
	
	private EntitySet<tb_Question> _tb_Question;
	
	private EntitySet<tb_Answer> _tb_Answer;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMarkChanging(System.Nullable<int> value);
    partial void OnMarkChanged();
    partial void OnRewardMarkChanging(System.Nullable<int> value);
    partial void OnRewardMarkChanged();
    partial void OnPaidMarkChanging(System.Nullable<int> value);
    partial void OnPaidMarkChanged();
    partial void OnACountChanging(System.Nullable<int> value);
    partial void OnACountChanged();
    partial void OnAAcceptCountChanging(System.Nullable<int> value);
    partial void OnAAcceptCountChanged();
    partial void OnQSolvedCountChanging(System.Nullable<int> value);
    partial void OnQSolvedCountChanged();
    partial void OnQUnsolveCountChanging(System.Nullable<int> value);
    partial void OnQUnsolveCountChanged();
    partial void OnQCancelledCountChanging(System.Nullable<int> value);
    partial void OnQCancelledCountChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    #endregion
	
	public tb_UserInfo()
	{
		this._tb_Question = new EntitySet<tb_Question>(new Action<tb_Question>(this.attach_tb_Question), new Action<tb_Question>(this.detach_tb_Question));
		this._tb_Answer = new EntitySet<tb_Answer>(new Action<tb_Answer>(this.attach_tb_Answer), new Action<tb_Answer>(this.detach_tb_Answer));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(100)")]
	public string UserName
	{
		get
		{
			return this._UserName;
		}
		set
		{
			if ((this._UserName != value))
			{
				this.OnUserNameChanging(value);
				this.SendPropertyChanging();
				this._UserName = value;
				this.SendPropertyChanged("UserName");
				this.OnUserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(20)")]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="Char(2)")]
	public string Sex
	{
		get
		{
			return this._Sex;
		}
		set
		{
			if ((this._Sex != value))
			{
				this.OnSexChanging(value);
				this.SendPropertyChanging();
				this._Sex = value;
				this.SendPropertyChanged("Sex");
				this.OnSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
	public System.Nullable<int> Mark
	{
		get
		{
			return this._Mark;
		}
		set
		{
			if ((this._Mark != value))
			{
				this.OnMarkChanging(value);
				this.SendPropertyChanging();
				this._Mark = value;
				this.SendPropertyChanged("Mark");
				this.OnMarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RewardMark", DbType="Int")]
	public System.Nullable<int> RewardMark
	{
		get
		{
			return this._RewardMark;
		}
		set
		{
			if ((this._RewardMark != value))
			{
				this.OnRewardMarkChanging(value);
				this.SendPropertyChanging();
				this._RewardMark = value;
				this.SendPropertyChanged("RewardMark");
				this.OnRewardMarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaidMark", DbType="Int")]
	public System.Nullable<int> PaidMark
	{
		get
		{
			return this._PaidMark;
		}
		set
		{
			if ((this._PaidMark != value))
			{
				this.OnPaidMarkChanging(value);
				this.SendPropertyChanging();
				this._PaidMark = value;
				this.SendPropertyChanged("PaidMark");
				this.OnPaidMarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACount", DbType="Int")]
	public System.Nullable<int> ACount
	{
		get
		{
			return this._ACount;
		}
		set
		{
			if ((this._ACount != value))
			{
				this.OnACountChanging(value);
				this.SendPropertyChanging();
				this._ACount = value;
				this.SendPropertyChanged("ACount");
				this.OnACountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AAcceptCount", DbType="Int")]
	public System.Nullable<int> AAcceptCount
	{
		get
		{
			return this._AAcceptCount;
		}
		set
		{
			if ((this._AAcceptCount != value))
			{
				this.OnAAcceptCountChanging(value);
				this.SendPropertyChanging();
				this._AAcceptCount = value;
				this.SendPropertyChanged("AAcceptCount");
				this.OnAAcceptCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QSolvedCount", DbType="Int")]
	public System.Nullable<int> QSolvedCount
	{
		get
		{
			return this._QSolvedCount;
		}
		set
		{
			if ((this._QSolvedCount != value))
			{
				this.OnQSolvedCountChanging(value);
				this.SendPropertyChanging();
				this._QSolvedCount = value;
				this.SendPropertyChanged("QSolvedCount");
				this.OnQSolvedCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUnsolveCount", DbType="Int")]
	public System.Nullable<int> QUnsolveCount
	{
		get
		{
			return this._QUnsolveCount;
		}
		set
		{
			if ((this._QUnsolveCount != value))
			{
				this.OnQUnsolveCountChanging(value);
				this.SendPropertyChanging();
				this._QUnsolveCount = value;
				this.SendPropertyChanged("QUnsolveCount");
				this.OnQUnsolveCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QCancelledCount", DbType="Int")]
	public System.Nullable<int> QCancelledCount
	{
		get
		{
			return this._QCancelledCount;
		}
		set
		{
			if ((this._QCancelledCount != value))
			{
				this.OnQCancelledCountChanging(value);
				this.SendPropertyChanging();
				this._QCancelledCount = value;
				this.SendPropertyChanged("QCancelledCount");
				this.OnQCancelledCountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> CreatedDate
	{
		get
		{
			return this._CreatedDate;
		}
		set
		{
			if ((this._CreatedDate != value))
			{
				this.OnCreatedDateChanging(value);
				this.SendPropertyChanging();
				this._CreatedDate = value;
				this.SendPropertyChanged("CreatedDate");
				this.OnCreatedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_UserInfo_tb_Question", Storage="_tb_Question", ThisKey="Code", OtherKey="UserCode")]
	public EntitySet<tb_Question> tb_Question
	{
		get
		{
			return this._tb_Question;
		}
		set
		{
			this._tb_Question.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_UserInfo_tb_Answer", Storage="_tb_Answer", ThisKey="Code", OtherKey="UserCode")]
	public EntitySet<tb_Answer> tb_Answer
	{
		get
		{
			return this._tb_Answer;
		}
		set
		{
			this._tb_Answer.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_tb_Question(tb_Question entity)
	{
		this.SendPropertyChanging();
		entity.tb_UserInfo = this;
	}
	
	private void detach_tb_Question(tb_Question entity)
	{
		this.SendPropertyChanging();
		entity.tb_UserInfo = null;
	}
	
	private void attach_tb_Answer(tb_Answer entity)
	{
		this.SendPropertyChanging();
		entity.tb_UserInfo = this;
	}
	
	private void detach_tb_Answer(tb_Answer entity)
	{
		this.SendPropertyChanging();
		entity.tb_UserInfo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_QuestionCatalog")]
public partial class vw_QuestionCatalog
{
	
	private string _Code;
	
	private string _Name;
	
	private System.Nullable<int> _qcnt;
	
	private int _acnt;
	
	private string _lastTitle;
	
	private string _lastCode;
	
	public vw_QuestionCatalog()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this._Code = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50)")]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this._Name = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qcnt", DbType="Int")]
	public System.Nullable<int> qcnt
	{
		get
		{
			return this._qcnt;
		}
		set
		{
			if ((this._qcnt != value))
			{
				this._qcnt = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acnt", DbType="Int NOT NULL")]
	public int acnt
	{
		get
		{
			return this._acnt;
		}
		set
		{
			if ((this._acnt != value))
			{
				this._acnt = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastTitle", DbType="NVarChar(100)")]
	public string lastTitle
	{
		get
		{
			return this._lastTitle;
		}
		set
		{
			if ((this._lastTitle != value))
			{
				this._lastTitle = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastCode", DbType="VarChar(50)")]
	public string lastCode
	{
		get
		{
			return this._lastCode;
		}
		set
		{
			if ((this._lastCode != value))
			{
				this._lastCode = value;
			}
		}
	}
}
#pragma warning restore 1591
